version: '3.8'
services:
    mongodb:
        image: 'mongo'

    backend:
        build: ./backend
        ports:
            - '5000:5000'
        volumes:
            - ./backend:/app
            - /app/node_modules
        depends_on:
            - mongodb

    frontend:
        build: ./frontend
        ports:
            - '80:80'
        stdin_open: true
        tty: true
        depends_on:
            - backend
