version: '3.8'
services:
    mongodb:
        image: mongo
        restart: unless-stopped
        env_file: ./.env
        environment:
            - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
            - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
        ports:
            - 27017:27017
        volumes:
            - db:/data/db
        networks:
            net:
                ipv4_address: 172.18.0.5

    backend:
        restart: unless-stopped
        build:
            context: backend
            target: production
            dockerfile: Dockerfile
        ports:
            - '5000:5000'
        volumes:
            - media:/usr/src/backend/media
        depends_on:
            - mongodb
        networks:
            net:
                ipv4_address: 172.18.0.4

    frontend:
        restart: unless-stopped
        build:
            context: frontend
            target: production
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        depends_on:
            - backend
        networks:
            net:
                ipv4_address: 172.18.0.3

    nginx:
        image: 'jc21/nginx-proxy-manager:latest'
        restart: unless-stopped
        ports:
            - '80:80'
            - '81:81'
            - '443:443'
        volumes:
            - ./data:/data
            - ./letsencrypt:/etc/letsencrypt
        networks:
            net:
                ipv4_address: 172.18.0.2

volumes:
    db:
    media:

networks:
    net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.18.0.0/24
        driver_opts:
            com.docker.network.bridge.name: common-bridge
