version: '3.8'
services:
    # mongodb:
    #     image: 'mongo'
    #     restart: on-failure
    #     ports:
    #         - '27017:27017'

    backend:
        restart: on-failure
        build:
            context: ./backend
            dockerfile: Dockerfile
        volumes:
            - ./backend:/app
            - /app/node_modules
        ports:
            - '5000:5000'

    frontend:
        build:
            dockerfile: Dockerfile
            context: ./frontend
        volumes:
            - /app/node_modules
            - ./frontend:/app
        ports:
            - '80:80'
            - '443:443'

    nginx:
        image: 'jc21/nginx-proxy-manager:latest'
        restart: unless-stopped
        ports:
            - '81:81'

        volumes:
            - ./data:/data
            - ./letsencrypt:/etc/letsencrypt
