version: '3.8'
services:
    # mongodb:
    #     image: 'mongo'
    #     restart: on-failure
    #     ports:
    #         - '27017:27017'

    backend:
        restart: on-failure
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - '5000:5000'
        volumes:
            - ./backend:/app
            - /app/node_modules
        depends_on:
            - mongodb

    frontend:
        restart: on-failure
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        stdin_open: true
        tty: true
        depends_on:
            - backend

    nginx:
        image: 'jc21/nginx-proxy-manager:latest'
        restart: unless-stopped
        ports:
            - '80:80'
            - '81:81'
            - '443:443'
        volumes:
            - ./data:/data
            - ./letsencrypt:/etc/letsencrypt
