version: "3.8"
services:
  postgres:
    image: postgres:alpine
    restart: unless-stopped
    ports:
      - 5435:5432
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - strapi-data:/var/lib/postgresql/data/

volumes:
  strapi-data:
