version: '3.8'
services:
    # mongodb:
    #     image: 'mongo'
    #     restart: on-failure
    #     ports:
    #         - '27017:27017'

    backend:
        restart: on-failure
        build:
            context: ./backend
            dockerfile: Dockerfile
        volumes:
            - ./backend:/app
            - /app/node_modules
        # depends_on:
        #     - mongodb

    frontend:
        build:
            dockerfile: Dockerfile
            context: ./frontend
        volumes:
            - /app/node_modules
            - ./frontend:/app
        links:
            - backend

    nginx:
        restart: unless-stopped
        build:
            dockerfile: Dockerfile
            context: ./nginx
        ports:
            - '80:80'
            - '81:81'
            - '443:443'
        # volumes:
        #     - ./data:/data
        #     - ./letsencrypt:/etc/letsencrypt
