version: '3.8'
services:
    backend:
        restart: unless-stopped
        build:
            context: ./backend
            dockerfile: Dockerfile
        volumes:
            - /app/node_modules
            - ./backend:/app
        ports:
            - '5000:5000'

    frontend:
        restart: unless-stopped
        build:
            context: ./frontend
            dockerfile: Dockerfile
        volumes:
            - /app/node_modules
            - ./frontend:/app
        ports:
            - '3000:3000'
        depends_on:
            - backend

    nginx:
        image: 'jc21/nginx-proxy-manager:latest'
        restart: unless-stopped
        ports:
            - '80:80'
            - '81:81'
            - '443:443'
        volumes:
            - ./data:/data
            - ./letsencrypt:/etc/letsencrypt
