version: '3.8'
services:
  postgres:
    container_name: postgres_db
    image: postgres:alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      net:
        ipv4_address: 172.18.0.6

  maildev:
    build:
      context: .
      dockerfile: maildev.Dockerfile
    ports:
      - ${MAIL_CLIENT_PORT}:1080
      - ${MAIL_PORT}:1025
    networks:
      net:
        ipv4_address: 172.18.0.7

  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4
  #   ports:
  #     - '8080:80'
  #   volumes:
  #     - /data/pgadmin:/root/.pgadmin
  #   env_file:
  #     - .env
  #   links:
  #     - postgres

  server:
    container_name: server
    restart: unless-stopped
    build:
      context: server
    ports:
      - '5000:5000'
    depends_on:
      - postgres
    volumes:
      - ./server/media/og:/usr/src/server/media/og
      - media:/usr/src/server/media
    networks:
      net:
        ipv4_address: 172.18.0.5

  client:
    container_name: client
    restart: unless-stopped
    build:
      context: client
    ports:
      - '3000:3000'
    depends_on:
      - server
    networks:
      net:
        ipv4_address: 172.18.0.4

  # dashboard:
  #   container_name: dashboard
  #   restart: unless-stopped
  #   build:
  #     context: dashboard
  #   ports:
  #     - '3001:3001'
  #   depends_on:
  #     - server
  #   networks:
  #     net:
  #       ipv4_address: 172.18.0.3

  nginx:
    container_name: nginx
    restart: unless-stopped
    build:
      context: nginx
      target: prod
    ports:
      - '80:80'
      - '443:443'
    networks:
      net:
        ipv4_address: 172.18.0.2

volumes:
  pgdata:
  media:

networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24
    driver_opts:
      com.docker.network.bridge.name: common-bridge
