version: '3.8'
services:
    backend:
        restart: unless-stopped
        build:
            context: backend
            target: production
            dockerfile: Dockerfile
        ports:
            - '5000:5000'
        networks:
            default:
                ipv4_address: 172.17.0.5

    frontend:
        restart: unless-stopped
        build:
            context: frontend
            target: production
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        depends_on:
            - backend
        networks:
            default:
                ipv4_address: 172.17.0.4

    nginx:
        image: 'jc21/nginx-proxy-manager:latest'
        restart: unless-stopped
        ports:
            - '80:80'
            - '81:81'
            - '443:443'
        volumes:
            - ./data:/data
            - ./letsencrypt:/etc/letsencrypt
        networks:
            default:
                ipv4_address: 172.17.0.3

networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.17.0.0/24
        driver_opts:
            com.docker.network.bridge.name: common-bridge
